# Generated by Django 4.1.1 on 2022-09-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_alter_train_from_city_alter_train_to_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainTest',
        ),
    ]
